name: repo-sync
on:
  schedule:
  - cron:  "*/15 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync-LineageOS
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "LineageOS/android_vendor_lineage"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}

